sudo: false
language: node_js
cache:
    directories:
        - node_modules
node_js: 10.15.0
branches:
    only:
        - master
        - /^greenkeeper/.*$/
notifications:
    email: false
script:
    - npm run validate
after_success:
    - npm run report-coverage
    - npm run semantic-release
